project:
  type: website
  output-dir: docs

website:
  title: "JacobO-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: final-portfolio/FinalProject.qmd
        text: "Project Portfolio"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

